### ISSUE TITLE
Directionality not indicated in chart

### ISSUE THREAD

**Issue by jeffb-stell** [mda590/cloudping.co#1]
ping results for us-east-1 -> ca-central-1 seem to be different than ca-central-1 -> us-east-1 in the chart, however the chart gives no indication of directionality.

It might be better to average the directions so that the boxes are equal however the user looks up values (more typical on charts these types), although that's more work than setting labels.

**Comment by mda590** [comment]
Thanks for the feedback - definitely agree with what you're saying! I am going to start with adding some labels, but I like the end goal of having the average of the 2 directions.
