### ISSUE TITLE
On top of region name, let's add the location name.

### ISSUE THREAD

**Issue by tomekit** [mda590/cloudping.co#19]
Just a quick thought. 
I believe that adding the region location name (e.g. Tokyo or Ireland) would help reading that list and have better idea if traffic e.g. from Tokyo flows through US or Asia.

**Comment by zt-initech** [comment]
names are for example here: https://docs.aws.amazon.com/general/latest/gr/rande.html

**Comment by mda590** [comment]
This is added in the newly deployed version.
