### ISSUE TITLE
Why the statistic look impossible?

### ISSUE THREAD

**Issue by bertpubble** [mda590/cloudping.co#25]
<img width="1431" alt="Screen Shot 2019-04-26 at 2 54 56 PM" src="https://user-images.githubusercontent.com/19281825/56792234-5a5a5100-6833-11e9-9551-c21f2df5c22e.png">
I think there are something wrong as shown in picture.

**Comment by mda590** [comment]
This was a bug and was previously resolved - it is certainly resolved in the newly deployed version.
