### ISSUE TITLE
Add GovCloud to Cloudping.co

### ISSUE THREAD

**Issue by Kcoppage** [mda590/cloudping.co#3]
Matt, sometime in the future can you add an entry for the GovCloud?  It would be very useful for some of us.  thanks.

**Comment by Kcoppage** [comment]
Matt, now with Govcloud (East) in play we could use both Govcloud East and Govcloud West on the display.  I understand that US-WEST-1 and US-EAST-2 are essentially the same timings.  It would just be useful to delineate these site.  If you think its worth your time.  Maybe this request is not technically possible do to the secure nature of the Govcloud VPCs.  Thank you.......

**Comment by PatMyron** [comment]
https://github.com/mda590/cloudping.co/pull/18

**Comment by mda590** [comment]
Will track this work in #30.
