### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by martyspiewak** [mda590/cloudping.co#51]
Hi!

The [cloudping website](https://www.cloudping.co/) seems to be down- I'm getting:
```
This site can’t be reached

www.cloudping.co’s server IP address could not be found.
```
I've tried this on multiple browsers and also confirmed that others are experiencing the same issue. Are there plans to fix this?

Thanks!

**Comment by iatpatelishan** [comment]
+1

**Comment by mda590** [comment]
Cloudping is back up and running! Major apologies for that extended downtime. New UI and API coming soon!

**Comment by jthomasser** [comment]
thanks!

**Comment by martyspiewak** [comment]
Thank you!
